version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Django tests
          command: ./IncomeExpenseTrackerAPI/manage.py test

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      # - run:
      #     name: Install Zappa
      #     command: pip install zappa
      # - run:
      #     name: Configure AWS CLI
      #     command: |
      #       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      #       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      #       aws configure set default.region $AWS_DEFAULT_REGION
      #       aws configure set default.output json
      # - run:
      #     name: Deploy with Zappa
      #     command: zappa update dev

workflows:
  main:
    jobs:
      - build-and-test
      # Uncomment the following line to include deployment
      # - deploy:
      #     requires:
      #       - build-and-test
